### ISSUE TITLE
Saying thanks!

### ISSUE THREAD

**Issue by lirantal** [OWASP/NodeGoat#109]
Hi Guys,

I wanted to chime in and say thanks and appreciate the work on this project which is a great asset for educating on security.

Me and a cool bunch of people from the JavaScript community of Cluj, Romania saying thanks ❤️ 

![img_20171110_110459 1](https://user-images.githubusercontent.com/316371/32690494-5f9d0656-c700-11e7-8896-93ed0682d5de.jpg)

**Comment by ckarande** [comment]
That is awesome. Thank you Liran for spreading the knowledge and being a
key contributor to the project.

Best,

Chetan

On Nov 11, 2017 9:50 AM, "Liran Tal" <notifications@github.com> wrote:

Hi Guys,

I wanted to chime in and say thanks and appreciate the work on this project
which is a great asset for educating on security.

Me and a cool bunch of people from the JavaScript community of Cluj,
Romania saying thanks ❤️

[image: img_20171110_110459 1]
<https://user-images.githubusercontent.com/316371/32690494-5f9d0656-c700-11e7-8896-93ed0682d5de.jpg>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OWASP/NodeGoat/issues/109>, or mute the thread

**Comment by ckarande** [comment]
That is awesome. Thank you Liran for spreading the knowledge and being a
key contributor to the project.

Best,

Chetan

**Comment by lirantal** [comment]
having fun doing it so the pleasure is mine :-)
