### ISSUE TITLE
Integrate and test ZAP API  

### ISSUE THREAD

**Issue by ckarande** [OWASP/NodeGoat#60]
Integrate and test ZAP API for all 3 deployment mechanisms.

Based on discussion with @binarymist, Zap API can live in a docker image.  Wavsep and Zap API can stay on one machine on AWS, each in their on docker containers. So it seems possible to integrate ZAP APIs with all of the three deployment scenarios of Nodegoat (local , heroku, and docker image).  This issue is added to test and verify it.

**Comment by binarymist** [comment]
Cheers. It's now in my personal Todo list.

**Comment by binarymist** [comment]
Any thoughts on what you would like to achieve with this @ckarande ?

**Comment by binarymist** [comment]
I've worked through and now have several scenarios covered in my wiki. I started a branch (https://github.com/binarymist/NodeGoat/tree/ContainerisedZapNodeGoatAndDb) which containerises all components, but then thought that there is probably little point in this, as NodeGoat really exists for hands-on education and training and the best approach I think is to have Zap in a container or otherwise running and any security regression tests able to be seen running. I'm going to setup Zap and NodeGoat in a VM as I and the students that have taken my trainings on this think a simple VM with the components setup and ready to run would be the quickest and easiest approach. Feel free to re-open or offer any thoughts you have.

**Comment by mostafahussein** [comment]
Is there anything that i can do to complete this ? let me know if you need any help

**Comment by binarymist** [comment]
I think this can be closed.

I've finished the new [ZAP Node APII](https://github.com/zaproxy/zap-api-nodejs)

I have a [dynamic number](https://gitlab.com/purpleteam-labs/purpleteam-lambda/blob/master/app-slave-provisioner/index.js) of [app scanners](https://gitlab.com/purpleteam-labs/purpleteam-s2-containers/blob/master/app-slave/docker-compose.yml) running based on the [build user config](https://gitlab.com/purpleteam-labs/purpleteam/blob/master/testResources/jobs/job_0.1.0-alpha.1#L21-28) file.

There's really nothing to do here anymore.

**Comment by ckarande** [comment]
Thanks @binarymist .. Closing this issue.
